### ISSUE TITLE
Use case demo

### ISSUE THREAD

**Issue by jean-santos** [layer07/HWHash#1]
We should add a use case for those willing to give a try on the project!

**Comment by layer07** [comment]
Readme update with HWHash in action for CruelMonitor.
![Alt Text](https://dev.divinelain.com/SingleSensor.gif)

**Comment by Stephanowicz** [comment]
Hi, 
thx for Your program!
I just wonder who made CruelMonitor? I can't find it anywhere :D 


Cheers, Stephan

**Comment by layer07** [comment]
> Hi, thx for Your program! I just wonder who made CruelMonitor? I can't find it anywhere :D
> 
> Cheers, Stephan

Hi Stephan, thank you for your feedback, hummm, CruelMon is a Chinese software, I didn't develop it, it just uses HWHash, so I gotta check out with the guy who originally showed me the demo, and then I can come back to you! I don't think it was called CruelMon I just translated the Chinese letters hahaha.

XOXO,

D. Leatti

**Comment by Stephanowicz** [comment]
Ah, ok! xD

Thank You!
