### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by CruelPulsar** [layer07/HWHash#2]
System.InvalidOperationException: 'Cannot read HWINFO Shared Memory. Make sure that HWInfo is running and that you have admin privileges.'

I've checked admin privileges, and still not able to run, can you please assist?

**Comment by layer07** [comment]
There is no Shared Memory Stream or Instance to attach to.

This often happens if you're running HWiNFO but your sensors are not writing to the shared memory stream, make sure you run HWiNFO and go directly to sensors, leave it there.

Try it.

**Comment by CruelPulsar** [comment]
> There is no Shared Memory Stream or Instance to attach to.
> 
> This often happens if you're running HWiNFO but your sensors are not writing to the shared memory stream, make sure you run HWiNFO and go directly to sensors, leave it there.
> 
> Try it.

Oh, that was it then, lol sorry, working now.
Thanks

**Comment by layer07** [comment]
> > There is no Shared Memory Stream or Instance to attach to.
> > This often happens if you're running HWiNFO but your sensors are not writing to the shared memory stream, make sure you run HWiNFO and go directly to sensors, leave it there.
> > Try it.
> 
> Oh, that was it then, lol sorry, working now. Thanks

I'm glad to hear it worked, I'll be closing this issue then.
