### ISSUE TITLE
Any possibility of this working under Linux?

### ISSUE THREAD

**Issue by ElWizard666** [layer07/HWHash#4]
I managed to get it working on Windows 10, what would I need to have it working on Linux?

**Comment by layer07** [comment]
Well it HWHash itself can easily be compiled to a Linux binary, the issue is that HWiNFO doesn't work there.

You can find out more on HWiNFO forum.

**Comment by ElWizard666** [comment]
> Well it HWHash itself can easily be compiled to a Linux binary, the issue is that HWiNFO doesn't work there.
> 
> You can find out more on HWiNFO forum.

Hi, thanks.
I've visited their forum and noted that they do not have Linux Support. That is sad.
